apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-ckad-les-services-app-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application-a
  template:
    metadata:
      labels:
        app: application-a
    spec:
      containers:
      - name: conteneur1
        image: laurentsogeti/ckad_formation_service:0.0.2
        env:
            - name: NOM_POD
              valueFrom:
                fieldRef:
                    fieldPath: metadata.name
            -  name: NOM_APP
               value: application-a

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-ckad-les-services-app-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application-b
  template:
    metadata:
      labels:
        app: application-b
    spec:
      containers:
      - name: conteneur1
        image: laurentsogeti/ckad_formation_service:0.0.2
        env:
            - name: NOM_POD
              valueFrom:
                fieldRef:
                    fieldPath: metadata.name
            -  name: NOM_APP
               value: application-b
