apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-ckad-les-services
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application-a
  template:
    metadata:
      labels:
        app: application-a
    spec:
      containers:
      - name: conteneur1
        image: laurentsogeti/pod_showname_formation_ckad:0.0.3
        env:
            - name: NOM_POD
              valueFrom:
                fieldRef:
                fieldPath: metadata.name
            -  name: NOM_APP
               value: application-a 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-ckad-les-services
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application-b
  template:
    metadata:
      labels:
        app: application-b
    spec:
      spec:
      containers:
      - name: conteneur1
        image: laurentsogeti/pod_showname_formation_ckad:0.0.3
