apiVersion: v1
kind: Service
metadata:
  name: my-expose-app-a-loadbalancer
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: application-a
  sessionAffinity: None
  type: LoadBalancer
