apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: my-expose-app-a-nodeport
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: application-a
  type: NodePort
status:
  loadBalancer: {}