apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-bar-to-foo
  namespace: foo-ns
spec:
  podSelector: {} # Cible tous les pods de foo-ns
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          labels-namespace: bar-ns
  egress:
  - to: 
    - namespaceSelector: 
        matchLabels: 
          labels-namespace: bar-ns
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-bar-to-foo
  namespace: bar-ns
spec:
  podSelector: {} # Cible tous les pods de foo-ns
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          labels-namespace: foo-ns
  egress:
  - to: 
    - namespaceSelector: 
        matchLabels: 
          labels-namespace: foo-ns

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-unautrebar42-dns
  namespace: bar-ns
spec:
  podSelector:
    matchLabels: 
      app: test42
  policyTypes:
  - Egress
  egress:
  - to:
    ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
