apiVersion: v1
kind: Secret
metadata:
  name: mon-premier-secret
type: Opaque
data:
  username: YWRtaW4=  # Equivalent à "admin" en base64
  password: cGFzc3dvcmQ=  # Equivalent à "password" en base64


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: mon-premier-secret
      containers:
      - name: my-container
        image: registry.k8s.io/busybox
        command:
          - "sh"
          - "-c"
          - |
            ls -l /etc/secret-volume
            sleep 10000
        envFrom:
        - secretRef:
            name: mon-premier-secret
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"