apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  annotations:
    kubernetes.io/change-cause: initial release
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: nginx:1.26.3
