apiVersion: v1
kind: Pod
metadata:
  name: web-dev
  labels:
    tier: frontend
spec:
  containers:
    - name: web-dev
      image: nginx:alpine
      env:
        - name: APP_ENV
          value: development
