apiVersion: v1
kind: Pod
metadata:
  name: probe-web
spec:
  containers:
    - name: web
      image: nginx:1.27.3
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /not-ready
          port: 8080
        initialDelaySeconds: 2
      livenessProbe:
        httpGet:
          path: /not-alive
          port: 8080
        initialDelaySeconds: 300
