apiVersion: v1
kind: Service
metadata:
  name: rolling-db-headless
spec:
  clusterIP: None
  selector:
    app: rolling-db
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rolling-db
spec:
  serviceName: rolling-db-headless
  replicas: 3
  selector:
    matchLabels:
      app: rolling-db
  template:
    metadata:
      labels:
        app: rolling-db
    spec:
      containers:
        - name: db
          image: nginx:1.26.3
