apiVersion: batch/v1
kind: Job
metadata:
  name: formation-ckad-job
spec:
  template:
    spec:
      containers:
      - name: random-job
        image: busybox
        command: ["sh", "-c", "date; echo 'Arrêt prévu dans 5 secondes'; sleep 5"]
      restartPolicy: Never 