apiVersion: v1
kind: Pod
metadata:
  name: formation-ckad-multi-container-pod
spec:
  containers:
  - name: conteneur1
    image: busybox
    command: ["sh", "-c", "echo 'Bonjour Je suis conteneur1'; sleep 10000"]
  - name: conteneur2
    image: ubuntu:latest
    command: ["sh", "-c", "echo 'Bonjour Je suis conteneur2'; sleep 10000"]