apiVersion: batch/v1
kind: CronJob
metadata:
  name: mon-cronjob
spec:
  schedule: "3 10 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: task-exec
            image: alpine
            command: ["/bin/sh" ,"-c" ,"echo \"Tâche exécutée à $(date)\""]
          restartPolicy: Never
