FROM nginx:1.27.3

# Copier le script run.sh dans le conteneur
COPY run_service.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/run_service.sh
# Exposer le port 80 (port par défaut de Nginx)
EXPOSE 80

# Commandes à exécuter au démarrage du conteneur
CMD ["/usr/local/bin/run_service.sh"]