FROM nginx:latest

# Copier le script run.sh dans le conteneur
COPY run.sh /usr/local/bin/

# Exposer le port 80 (port par défaut de Nginx)
EXPOSE 80

# Commandes à exécuter au démarrage du conteneur
CMD ["/usr/local/bin/run.sh"]