FROM ubuntu:22.04

# Installer les outils réseau
RUN apt-get update && apt-get install -y netcat ping host

# Copier le script run.sh dans le conteneur
COPY run_service.sh /usr/local/bin/
RUN  chmod +x /usr/local/bin/run_service.sh

# Exposer le port si nécessaire (ajuster si besoin)
EXPOSE 8080

# Commandes à exécuter au démarrage du conteneur
CMD ["/usr/local/bin/run_service.sh"]