###  POUR TESTER: kubectl auth can-i create namespaces --as=system:serviceaccount:default:mon-service-account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-reader
rules:
- apiGroups: [""] # Groupe d'API core
  resources: ["namespaces"]
  verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mon-service-account-namespaces-reader
subjects:
- kind: ServiceAccount
  name: mon-service-account # Le nom de votre ServiceAccount
  namespace: default # Le namespace de votre ServiceAccount
roleRef:
  kind: ClusterRole
  name: namespace-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace:  default
rules:
- apiGroups: [""] # Groupe d'API core
  resources: ["pods"]
  verbs: ["list","get"]
- apiGroups: [""] # Groupe d'API core
  resources: ["secrets"]
  verbs: ["delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mon-service-account-pod-reader
  namespace:  default
subjects:
- kind: ServiceAccount
  name: mon-service-account # Le nom de votre ServiceAccount
  namespace: default # Le namespace de votre ServiceAccount
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io