apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev  

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: prod 

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    lelabel: monitoring-label 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      test:  nginx-dev-label
  template:
    metadata:
      labels:
        test:  nginx-dev-label
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      app: mon-app # Exemple de label supplémentaire
  template:
    metadata:
      labels:
        app: nginx
        app: mon-app # Exemple de label supplémentaire
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-monitoring
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
     type:  monitoring
  template:
    metadata:
      labels:
         type:  monitoring
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dev
spec:
  selector:
    test:  nginx-dev-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: prod
spec:
  selector:
    app: mon-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: monitoring
spec:
  selector:
    type: monitoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: google
  namespace:  prod
spec:
  type: ExternalName
  externalName: exemple.com

---
apiVersion: v1
kind: Service
metadata:
  name: google
  namespace:  dev
spec:
  type: ExternalName
  externalName: exemple.com